FROM ubuntu:16.04 as ubuntu16

RUN mkdir TPDockerSampleApp
WORKDIR /TPDockerSampleApp

# ADD ./lib ./lib
# ADD ./haarcascades ./haarcascades
# ADD ./target/fatjar-0.0.1-SNAPSHOT.jar ./fatjar-0.0.1-SNAPSHOT.jar

EXPOSE 8080

RUN apt update
RUN apt install -y openjdk-8-jre

RUN apt-get -y install -f libpng16-16 &&\
    apt-get -y install -f libjasper1 &&\
    apt-get -y install -f libdc1394-22

# CMD [ "java", "-Djava.library.path=lib/", "-jar", "fatjar-0.0.1-SNAPSHOT.jar" ]