FROM ubuntu:16.04

# EXPOSE 8080

RUN apt-get update &&\
    apt-get install -y openjdk-8-jdk &&\
    apt-get install -y maven &&\
    apt-get install -y git

# RUN apt-get -y install -f libpng16-16 &&\
#     apt-get -y install -f libjasper1 &&\
#     apt-get -y install -f libdc1394-22

RUN git clone https://github.com/barais/TPDockerSampleApp
WORKDIR /TPDockerSampleApp

RUN mvn install:install-file -Dfile=./lib/opencv-3410.jar \
    -DgroupId=org.opencv  -DartifactId=opencv -Dversion=3.4.10 -Dpackaging=jar
RUN mvn package

# CMD [ "java", "-Djava.library.path=lib/", "-jar", "target/fatjar-0.0.1-SNAPSHOT.jar" ]